<?php

declare(strict_types = 1);

/*
 * This file is part of PHP CS Fixer.
 *
 * (c) Fabien Potencier <fabien@symfony.com>
 *     Dariusz Rumiński <dariusz.ruminski@gmail.com>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

use Phpro\SoapClient\Soap\ClassMap\ClassMap;
use Phpro\SoapClient\Soap\ClassMap\ClassMapCollection;

return new ClassMapCollection([
    new ClassMap('Array', \Etrias\MagentoConnector\SoapTypes\ArrayType::class),
    new ClassMap('Struct', \Etrias\MagentoConnector\SoapTypes\Struct::class),
    new ClassMap('duration', \Etrias\MagentoConnector\SoapTypes\Duration::class),
    new ClassMap('dateTime', \Etrias\MagentoConnector\SoapTypes\DateTime::class),
    new ClassMap('NOTATION', \Etrias\MagentoConnector\SoapTypes\NOTATION::class),
    new ClassMap('time', \Etrias\MagentoConnector\SoapTypes\Time::class),
    new ClassMap('date', \Etrias\MagentoConnector\SoapTypes\Date::class),
    new ClassMap('gYearMonth', \Etrias\MagentoConnector\SoapTypes\GYearMonth::class),
    new ClassMap('gYear', \Etrias\MagentoConnector\SoapTypes\GYear::class),
    new ClassMap('gMonthDay', \Etrias\MagentoConnector\SoapTypes\GMonthDay::class),
    new ClassMap('gDay', \Etrias\MagentoConnector\SoapTypes\GDay::class),
    new ClassMap('gMonth', \Etrias\MagentoConnector\SoapTypes\GMonth::class),
    new ClassMap('boolean', \Etrias\MagentoConnector\SoapTypes\Boolean::class),
    new ClassMap('base64Binary', \Etrias\MagentoConnector\SoapTypes\Base64Binary::class),
    new ClassMap('hexBinary', \Etrias\MagentoConnector\SoapTypes\HexBinary::class),
    new ClassMap('float', \Etrias\MagentoConnector\SoapTypes\Float::class),
    new ClassMap('double', \Etrias\MagentoConnector\SoapTypes\Double::class),
    new ClassMap('anyURI', \Etrias\MagentoConnector\SoapTypes\AnyURI::class),
    new ClassMap('QName', \Etrias\MagentoConnector\SoapTypes\QName::class),
    new ClassMap('string', \Etrias\MagentoConnector\SoapTypes\String::class),
    new ClassMap('normalizedString', \Etrias\MagentoConnector\SoapTypes\NormalizedString::class),
    new ClassMap('token', \Etrias\MagentoConnector\SoapTypes\Token::class),
    new ClassMap('language', \Etrias\MagentoConnector\SoapTypes\Language::class),
    new ClassMap('Name', \Etrias\MagentoConnector\SoapTypes\Name::class),
    new ClassMap('NMTOKEN', \Etrias\MagentoConnector\SoapTypes\NMTOKEN::class),
    new ClassMap('NCName', \Etrias\MagentoConnector\SoapTypes\NCName::class),
    new ClassMap('NMTOKENS', \Etrias\MagentoConnector\SoapTypes\NMTOKENS::class),
    new ClassMap('ID', \Etrias\MagentoConnector\SoapTypes\ID::class),
    new ClassMap('IDREF', \Etrias\MagentoConnector\SoapTypes\IDREF::class),
    new ClassMap('ENTITY', \Etrias\MagentoConnector\SoapTypes\ENTITY::class),
    new ClassMap('IDREFS', \Etrias\MagentoConnector\SoapTypes\IDREFS::class),
    new ClassMap('ENTITIES', \Etrias\MagentoConnector\SoapTypes\ENTITIES::class),
    new ClassMap('decimal', \Etrias\MagentoConnector\SoapTypes\Decimal::class),
    new ClassMap('integer', \Etrias\MagentoConnector\SoapTypes\Integer::class),
    new ClassMap('nonPositiveInteger', \Etrias\MagentoConnector\SoapTypes\NonPositiveInteger::class),
    new ClassMap('negativeInteger', \Etrias\MagentoConnector\SoapTypes\NegativeInteger::class),
    new ClassMap('long', \Etrias\MagentoConnector\SoapTypes\Long::class),
    new ClassMap('int', \Etrias\MagentoConnector\SoapTypes\Int::class),
    new ClassMap('short', \Etrias\MagentoConnector\SoapTypes\Short::class),
    new ClassMap('byte', \Etrias\MagentoConnector\SoapTypes\Byte::class),
    new ClassMap('nonNegativeInteger', \Etrias\MagentoConnector\SoapTypes\NonNegativeInteger::class),
    new ClassMap('unsignedLong', \Etrias\MagentoConnector\SoapTypes\UnsignedLong::class),
    new ClassMap('unsignedInt', \Etrias\MagentoConnector\SoapTypes\UnsignedInt::class),
    new ClassMap('unsignedShort', \Etrias\MagentoConnector\SoapTypes\UnsignedShort::class),
    new ClassMap('unsignedByte', \Etrias\MagentoConnector\SoapTypes\UnsignedByte::class),
    new ClassMap('positiveInteger', \Etrias\MagentoConnector\SoapTypes\PositiveInteger::class),
    new ClassMap('associativeEntity', \Etrias\MagentoConnector\SoapTypes\AssociativeEntity::class),
    new ClassMap('associativeMultiEntity', \Etrias\MagentoConnector\SoapTypes\AssociativeMultiEntity::class),
    new ClassMap('filters', \Etrias\MagentoConnector\SoapTypes\Filters::class),
    new ClassMap('complexFilter', \Etrias\MagentoConnector\SoapTypes\ComplexFilter::class),
    new ClassMap('apiMethodEntity', \Etrias\MagentoConnector\SoapTypes\ApiMethodEntity::class),
    new ClassMap('apiEntity', \Etrias\MagentoConnector\SoapTypes\ApiEntity::class),
    new ClassMap('existsFaltureEntity', \Etrias\MagentoConnector\SoapTypes\ExistsFaltureEntity::class),
    new ClassMap('storeEntity', \Etrias\MagentoConnector\SoapTypes\StoreEntity::class),
    new ClassMap('magentoInfoEntity', \Etrias\MagentoConnector\SoapTypes\MagentoInfoEntity::class),
    new ClassMap('directoryCountryEntity', \Etrias\MagentoConnector\SoapTypes\DirectoryCountryEntity::class),
    new ClassMap('directoryRegionEntity', \Etrias\MagentoConnector\SoapTypes\DirectoryRegionEntity::class),
    new ClassMap('customerCustomerEntityToCreate', \Etrias\MagentoConnector\SoapTypes\CustomerCustomerEntityToCreate::class),
    new ClassMap('customerCustomerEntity', \Etrias\MagentoConnector\SoapTypes\CustomerCustomerEntity::class),
    new ClassMap('customerGroupEntity', \Etrias\MagentoConnector\SoapTypes\CustomerGroupEntity::class),
    new ClassMap('customerAddressEntityCreate', \Etrias\MagentoConnector\SoapTypes\CustomerAddressEntityCreate::class),
    new ClassMap('customerAddressEntityItem', \Etrias\MagentoConnector\SoapTypes\CustomerAddressEntityItem::class),
    new ClassMap('catalogProductAdditionalAttributesEntity', \Etrias\MagentoConnector\SoapTypes\CatalogProductAdditionalAttributesEntity::class),
    new ClassMap('catalogProductEntity', \Etrias\MagentoConnector\SoapTypes\CatalogProductEntity::class),
    new ClassMap('catalogProductRequestAttributes', \Etrias\MagentoConnector\SoapTypes\CatalogProductRequestAttributes::class),
    new ClassMap('catalogProductReturnEntity', \Etrias\MagentoConnector\SoapTypes\CatalogProductReturnEntity::class),
    new ClassMap('catalogProductCreateEntity', \Etrias\MagentoConnector\SoapTypes\CatalogProductCreateEntity::class),
    new ClassMap('catalogProductAttributeSetEntity', \Etrias\MagentoConnector\SoapTypes\CatalogProductAttributeSetEntity::class),
    new ClassMap('catalogProductTypeEntity', \Etrias\MagentoConnector\SoapTypes\CatalogProductTypeEntity::class),
    new ClassMap('catalogProductTierPriceEntity', \Etrias\MagentoConnector\SoapTypes\CatalogProductTierPriceEntity::class),
    new ClassMap('catalogCategoryEntity', \Etrias\MagentoConnector\SoapTypes\CatalogCategoryEntity::class),
    new ClassMap('catalogCategoryEntityNoChildren', \Etrias\MagentoConnector\SoapTypes\CatalogCategoryEntityNoChildren::class),
    new ClassMap('catalogCategoryTree', \Etrias\MagentoConnector\SoapTypes\CatalogCategoryTree::class),
    new ClassMap('catalogCategoryEntityCreate', \Etrias\MagentoConnector\SoapTypes\CatalogCategoryEntityCreate::class),
    new ClassMap('catalogCategoryInfo', \Etrias\MagentoConnector\SoapTypes\CatalogCategoryInfo::class),
    new ClassMap('catalogAssignedProduct', \Etrias\MagentoConnector\SoapTypes\CatalogAssignedProduct::class),
    new ClassMap('catalogAttributeEntity', \Etrias\MagentoConnector\SoapTypes\CatalogAttributeEntity::class),
    new ClassMap('catalogAttributeOptionEntity', \Etrias\MagentoConnector\SoapTypes\CatalogAttributeOptionEntity::class),
    new ClassMap('catalogProductImageEntity', \Etrias\MagentoConnector\SoapTypes\CatalogProductImageEntity::class),
    new ClassMap('catalogProductAttributeMediaTypeEntity', \Etrias\MagentoConnector\SoapTypes\CatalogProductAttributeMediaTypeEntity::class),
    new ClassMap('catalogProductImageFileEntity', \Etrias\MagentoConnector\SoapTypes\CatalogProductImageFileEntity::class),
    new ClassMap('catalogProductAttributeMediaCreateEntity', \Etrias\MagentoConnector\SoapTypes\CatalogProductAttributeMediaCreateEntity::class),
    new ClassMap('catalogProductLinkEntity', \Etrias\MagentoConnector\SoapTypes\CatalogProductLinkEntity::class),
    new ClassMap('catalogProductLinkAttributeEntity', \Etrias\MagentoConnector\SoapTypes\CatalogProductLinkAttributeEntity::class),
    new ClassMap('catalogProductAttributeFrontendLabelEntity', \Etrias\MagentoConnector\SoapTypes\CatalogProductAttributeFrontendLabelEntity::class),
    new ClassMap('catalogProductAttributeEntityToCreate', \Etrias\MagentoConnector\SoapTypes\CatalogProductAttributeEntityToCreate::class),
    new ClassMap('catalogProductAttributeEntityToUpdate', \Etrias\MagentoConnector\SoapTypes\CatalogProductAttributeEntityToUpdate::class),
    new ClassMap('catalogProductAttributeEntity', \Etrias\MagentoConnector\SoapTypes\CatalogProductAttributeEntity::class),
    new ClassMap('catalogProductAttributeOptionLabelEntity', \Etrias\MagentoConnector\SoapTypes\CatalogProductAttributeOptionLabelEntity::class),
    new ClassMap('catalogProductAttributeOptionEntityToAdd', \Etrias\MagentoConnector\SoapTypes\CatalogProductAttributeOptionEntityToAdd::class),
    new ClassMap('catalogProductCustomOptionAdditionalFieldsEntity', \Etrias\MagentoConnector\SoapTypes\CatalogProductCustomOptionAdditionalFieldsEntity::class),
    new ClassMap('catalogProductCustomOptionToAdd', \Etrias\MagentoConnector\SoapTypes\CatalogProductCustomOptionToAdd::class),
    new ClassMap('catalogProductCustomOptionToUpdate', \Etrias\MagentoConnector\SoapTypes\CatalogProductCustomOptionToUpdate::class),
    new ClassMap('catalogProductCustomOptionInfoEntity', \Etrias\MagentoConnector\SoapTypes\CatalogProductCustomOptionInfoEntity::class),
    new ClassMap('catalogProductCustomOptionListEntity', \Etrias\MagentoConnector\SoapTypes\CatalogProductCustomOptionListEntity::class),
    new ClassMap('catalogProductCustomOptionTypesEntity', \Etrias\MagentoConnector\SoapTypes\CatalogProductCustomOptionTypesEntity::class),
    new ClassMap('catalogProductCustomOptionValueInfoEntity', \Etrias\MagentoConnector\SoapTypes\CatalogProductCustomOptionValueInfoEntity::class),
    new ClassMap('catalogProductCustomOptionValueListEntity', \Etrias\MagentoConnector\SoapTypes\CatalogProductCustomOptionValueListEntity::class),
    new ClassMap('catalogProductCustomOptionValueAddEntity', \Etrias\MagentoConnector\SoapTypes\CatalogProductCustomOptionValueAddEntity::class),
    new ClassMap('catalogProductCustomOptionValueUpdateEntity', \Etrias\MagentoConnector\SoapTypes\CatalogProductCustomOptionValueUpdateEntity::class),
    new ClassMap('salesOrderEntity', \Etrias\MagentoConnector\SoapTypes\SalesOrderEntity::class),
    new ClassMap('salesOrderListEntity', \Etrias\MagentoConnector\SoapTypes\SalesOrderListEntity::class),
    new ClassMap('salesOrderAddressEntity', \Etrias\MagentoConnector\SoapTypes\SalesOrderAddressEntity::class),
    new ClassMap('salesOrderItemEntity', \Etrias\MagentoConnector\SoapTypes\SalesOrderItemEntity::class),
    new ClassMap('orderItemIdQty', \Etrias\MagentoConnector\SoapTypes\OrderItemIdQty::class),
    new ClassMap('salesOrderPaymentEntity', \Etrias\MagentoConnector\SoapTypes\SalesOrderPaymentEntity::class),
    new ClassMap('salesOrderStatusHistoryEntity', \Etrias\MagentoConnector\SoapTypes\SalesOrderStatusHistoryEntity::class),
    new ClassMap('salesOrderShipmentEntity', \Etrias\MagentoConnector\SoapTypes\SalesOrderShipmentEntity::class),
    new ClassMap('salesOrderShipmentCommentEntity', \Etrias\MagentoConnector\SoapTypes\SalesOrderShipmentCommentEntity::class),
    new ClassMap('salesOrderShipmentTrackEntity', \Etrias\MagentoConnector\SoapTypes\SalesOrderShipmentTrackEntity::class),
    new ClassMap('salesOrderShipmentItemEntity', \Etrias\MagentoConnector\SoapTypes\SalesOrderShipmentItemEntity::class),
    new ClassMap('salesOrderInvoiceEntity', \Etrias\MagentoConnector\SoapTypes\SalesOrderInvoiceEntity::class),
    new ClassMap('salesOrderInvoiceItemEntity', \Etrias\MagentoConnector\SoapTypes\SalesOrderInvoiceItemEntity::class),
    new ClassMap('salesOrderInvoiceCommentEntity', \Etrias\MagentoConnector\SoapTypes\SalesOrderInvoiceCommentEntity::class),
    new ClassMap('salesOrderCreditmemoEntity', \Etrias\MagentoConnector\SoapTypes\SalesOrderCreditmemoEntity::class),
    new ClassMap('salesOrderCreditmemoItemEntity', \Etrias\MagentoConnector\SoapTypes\SalesOrderCreditmemoItemEntity::class),
    new ClassMap('salesOrderCreditmemoCommentEntity', \Etrias\MagentoConnector\SoapTypes\SalesOrderCreditmemoCommentEntity::class),
    new ClassMap('salesOrderCreditmemoData', \Etrias\MagentoConnector\SoapTypes\SalesOrderCreditmemoData::class),
    new ClassMap('catalogInventoryStockItemEntity', \Etrias\MagentoConnector\SoapTypes\CatalogInventoryStockItemEntity::class),
    new ClassMap('catalogInventoryStockItemUpdateEntity', \Etrias\MagentoConnector\SoapTypes\CatalogInventoryStockItemUpdateEntity::class),
    new ClassMap('shoppingCartAddressEntity', \Etrias\MagentoConnector\SoapTypes\ShoppingCartAddressEntity::class),
    new ClassMap('shoppingCartItemEntity', \Etrias\MagentoConnector\SoapTypes\ShoppingCartItemEntity::class),
    new ClassMap('shoppingCartPaymentEntity', \Etrias\MagentoConnector\SoapTypes\ShoppingCartPaymentEntity::class),
    new ClassMap('shoppingCartInfoEntity', \Etrias\MagentoConnector\SoapTypes\ShoppingCartInfoEntity::class),
    new ClassMap('shoppingCartTotalsEntity', \Etrias\MagentoConnector\SoapTypes\ShoppingCartTotalsEntity::class),
    new ClassMap('shoppingCartLicenseEntity', \Etrias\MagentoConnector\SoapTypes\ShoppingCartLicenseEntity::class),
    new ClassMap('shoppingCartProductEntity', \Etrias\MagentoConnector\SoapTypes\ShoppingCartProductEntity::class),
    new ClassMap('shoppingCartCustomerEntity', \Etrias\MagentoConnector\SoapTypes\ShoppingCartCustomerEntity::class),
    new ClassMap('shoppingCartCustomerAddressEntity', \Etrias\MagentoConnector\SoapTypes\ShoppingCartCustomerAddressEntity::class),
    new ClassMap('shoppingCartShippingMethodEntity', \Etrias\MagentoConnector\SoapTypes\ShoppingCartShippingMethodEntity::class),
    new ClassMap('shoppingCartPaymentMethodEntity', \Etrias\MagentoConnector\SoapTypes\ShoppingCartPaymentMethodEntity::class),
    new ClassMap('shoppingCartPaymentMethodResponseEntityArray', \Etrias\MagentoConnector\SoapTypes\ShoppingCartPaymentMethodResponseEntityArray::class),
    new ClassMap('giftMessageEntity', \Etrias\MagentoConnector\SoapTypes\GiftMessageEntity::class),
    new ClassMap('giftMessageResponse', \Etrias\MagentoConnector\SoapTypes\GiftMessageResponse::class),
    new ClassMap('giftMessageAssociativeProductsEntity', \Etrias\MagentoConnector\SoapTypes\GiftMessageAssociativeProductsEntity::class),
    new ClassMap('oppcwTransactionEntity', \Etrias\MagentoConnector\SoapTypes\OppcwTransactionEntity::class),
]);
